# Basic PPO Trainer Configuration
defaults:
  - _self_
  - env: cityflow

# Model configuration
model:
  base_model: "Qwen/Qwen2.5-0.5B-Instruct"
  experiment_name: "default-experiment"
  gradient_checkpointing: true

# Training parameters
training:
  train_batch_size: 4
  micro_batch_size: 4
  ppo_batch_size: 32
  max_turns: 2
  n_rollout: 4

# Optimization parameters
optimization:
  actor_lr: 1e-6
  critic_lr: 1e-5
  kl_coef: 0.001
  adv_estimator: brpo

# Dataset configuration
data:
  tokenizer: null
  train_files: ~/data/traffic/train.parquet
  val_files: ~/data/traffic/test.parquet
  train_data_num: null
  val_data_num: null
  prompt_key: prompt
  max_prompt_length: 1024
  max_response_length: 1024
  max_start_length: 256
  max_obs_length: 512
  val_batch_size: 1312
  return_raw_input_ids: False  # Set to true when tokenizers between policy and RM differ
  return_raw_chat: False
  shuffle_train_dataloader: True

# Actor, reference model, and rollout configuration
actor_rollout_ref:
  hybrid_engine: True
  model:
    path: ~/models/Qwen2.5-0.5B
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: False
    use_remove_padding: False
  actor:
    strategy: fsdp  # For backward-compatibility
    ppo_mini_batch_size: 256
    ppo_micro_batch_size: 64
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 16384 # n * ${data.max_prompt_length} + ${data.max_response_length}
    grad_clip: 1.0
    state_masking: False
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: False # True for GRPO
    kl_loss_coef: 0.001 # For GRPO
    kl_loss_type: low_var_kl # For GRPO
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1 # SP size
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.  # Total steps will be injected during runtime
      min_lr_ratio: null   # Only useful for warmup with cosine
      warmup_style: constant  # Select from constant/cosine
      total_training_steps: -1  # Must be overridden by program
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      grad_offload: False
      optimizer_offload: False
      fsdp_size: -1
      model_dtype: bfloat16
  ref:
    fsdp_config:
      param_offload: False
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
      model_dtype: bfloat16
      
    log_prob_micro_batch_size: 128
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # SP size
  rollout:
    name: vllm
    temperature: 1.0
    top_k: -1 # 0 for HF rollout, -1 for VLLM rollout
    top_p: 0.95
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    # VLLM rollout settings
    dtype: bfloat16 # Should align with FSDP
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 8192
    max_num_seqs: 1024
    log_prob_micro_batch_size: 128
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    # HF rollout settings
    do_sample: True
    # Number of responses (i.e., sample count)
    n: 1 # > 1 for GRPO
    n_agent: 1 # Used for agent tasks only

# Critic model configuration
critic:
  strategy: fsdp
  optim:
    lr: 1e-5
    lr_warmup_steps_ratio: 0.  # Total steps will be injected during runtime
    min_lr_ratio: null   # Only useful for warmup with cosine
    warmup_style: constant  # Select from constant/cosine
    total_training_steps: -1  # Must be overridden by program
  model:
    path: ${actor_rollout_ref.model.path}
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: False
    use_remove_padding: False
    fsdp_config:
      param_offload: False
      grad_offload: False
      optimizer_offload: False
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
  ppo_mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  ppo_micro_batch_size: ${actor_rollout_ref.actor.ppo_micro_batch_size}
  forward_micro_batch_size: ${critic.ppo_micro_batch_size}
  use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: 32768 # (${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}) * 2
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: 1 # SP size
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5

# Reward model configuration
reward_model:
  enable: False
  strategy: fsdp
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}  # Set to null if chat template is identical
    path: ~/models/FsfairX-LLaMA3-RM-v0.1
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: False
    fsdp_config:
      min_num_params: 0
      param_offload: False
  micro_batch_size: 64
  max_length: null
  ulysses_sequence_parallel_size: 1 # SP size
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}

# RL algorithm configuration
algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  no_think_rl: False
  kl_penalty: kl  # How to estimate KL divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.001
  state_masking:
    start_state_marker: "<start-state>"
    end_state_marker: "<end-state>"

# Training infrastructure settings
trainer:
  total_epochs: 30
  total_training_steps: null
  project_name: verl_examples
  experiment_name: gsm8k
  logger: [ 'console', 'wandb' ]
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: -1
  test_freq: -1
  critic_warmup: 0
  default_hdfs_dir: ~/experiments/gsm8k/ppo/${trainer.experiment_name}
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}

# Processing configuration
multi_processing: ray
max_turns: 2

# Environment configuration
env:
  name: sokoban

# Logging configuration (merged from both sections)
logging:
  mode: "['wandb']"
  log_images: True
  log_image_dir: log/trajectory
  log_image_step_size: 1
  log_n_image_per_batch: 4
  log_n_sample_per_batch: 1
